version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: inscriptions_db
      POSTGRES_USER: inscriptions_user
      POSTGRES_PASSWORD: inscriptions_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=postgres
      - DB_USERNAME=inscriptions_user
      - DB_PASSWORD=inscriptions_pass
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: