# .github/workflows/backend-ci.yml
name: Backend CI

on:
    push:
        paths:
            - "backend/**"
            - ".github/workflows/backend-ci.yml"
    pull_request:
        paths:
            - "backend/**"

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_PASSWORD: test
                    POSTGRES_USER: test
                    POSTGRES_DB: test
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 21 # ← Changé ici
              uses: actions/setup-java@v3
              with:
                  java-version: "21" # ← Changé ici
                  distribution: "temurin"

            - name: Cache Maven dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2

            - name: Run tests
              run: |
                  cd backend
                  mvn clean test

            - name: Generate test report
              uses: dorny/test-reporter@v1
              if: success() || failure()
              with:
                  name: Maven Tests
                  path: "backend/target/surefire-reports/*.xml"
                  reporter: java-junit

            - name: Build application
              run: |
                  cd backend
                  mvn clean package -DskipTests

            - name: Upload JAR
              uses: actions/upload-artifact@v3
              with:
                  name: backend-jar
                  path: backend/target/*.jar
