name: Frontend CI

on:
    push:
        branches: [main, develop]
        paths:
            - "inscriptions/inscriptions-frontend/**"
            - ".github/workflows/frontend-ci.yml"
    pull_request:
        branches: [main]
        paths:
            - "inscriptions/inscriptions-frontend/**"

jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./inscriptions/inscriptions-frontend

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "npm"
                  cache-dependency-path: ./inscriptions/inscriptions-frontend/package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm run test:ci

            - name: Build application
              run: |
                  if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
                    echo "Building for development..."
                    npm run build:dev
                  else
                    echo "Building for production..."
                    npm run build:prod
                  fi

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-dist
                  path: inscriptions/inscriptions-frontend/dist/
